In [1]:
import tensorflow as tf
import numpy as np
import cv2
import os
from tensorflow import keras
import time
from PIL import Image

In [2]:
size = 224

In [3]:
parent_dir = r'C:\Projects\Dataset\original_set'

categories = ['Facemask' , 'incorrect' , 'no_face_mask']


In [4]:
training_data = []

In [5]:
for category in categories:
    path = os.path.join(parent_dir , category)
    label = categories.index(category)
    for img in os.listdir(path):
        image = cv2.imread(os.path.join(path , img))
        image_rgb = cv2.cvtColor(image , cv2.COLOR_BGR2RGB)
        img_size = cv2.resize(image_rgb , (size , size))
        training_data.append([img_size , label])


In [6]:
import random

random.shuffle(training_data)

In [7]:
x = []
y = []

In [8]:
for features , label in training_data:
    x.append(features)
    y.append(label)

In [9]:
X = np.array(x).reshape(-1 , size , size , 3)
Y = np.array(y)

In [10]:
print(Y[0] , X[0])

1 [[[241 243 232]
  [240 242 231]
  [239 241 230]
  ...
  [145  83  36]
  [142  81  34]
  [147  86  39]]

 [[234 236 225]
  [234 236 225]
  [232 234 223]
  ...
  [149  87  40]
  [146  84  37]
  [146  86  36]]

 [[224 225 217]
  [223 224 216]
  [222 223 215]
  ...
  [154  90  42]
  [151  87  39]
  [146  84  33]]

 ...

 [[120  89  94]
  [127  96 101]
  [135 104 109]
  ...
  [100  50  23]
  [110  53  23]
  [138  78  44]]

 [[122  91  96]
  [130  99 104]
  [139 110 114]
  ...
  [101  54  26]
  [106  51  20]
  [119  60  26]]

 [[126  95 100]
  [131 100 105]
  [134 105 109]
  ...
  [102  55  27]
  [105  52  20]
  [104  48  13]]]


In [11]:
X = X/255.0

In [12]:
print(X[0])

[[[0.94509804 0.95294118 0.90980392]
  [0.94117647 0.94901961 0.90588235]
  [0.9372549  0.94509804 0.90196078]
  ...
  [0.56862745 0.3254902  0.14117647]
  [0.55686275 0.31764706 0.13333333]
  [0.57647059 0.3372549  0.15294118]]

 [[0.91764706 0.9254902  0.88235294]
  [0.91764706 0.9254902  0.88235294]
  [0.90980392 0.91764706 0.8745098 ]
  ...
  [0.58431373 0.34117647 0.15686275]
  [0.57254902 0.32941176 0.14509804]
  [0.57254902 0.3372549  0.14117647]]

 [[0.87843137 0.88235294 0.85098039]
  [0.8745098  0.87843137 0.84705882]
  [0.87058824 0.8745098  0.84313725]
  ...
  [0.60392157 0.35294118 0.16470588]
  [0.59215686 0.34117647 0.15294118]
  [0.57254902 0.32941176 0.12941176]]

 ...

 [[0.47058824 0.34901961 0.36862745]
  [0.49803922 0.37647059 0.39607843]
  [0.52941176 0.40784314 0.42745098]
  ...
  [0.39215686 0.19607843 0.09019608]
  [0.43137255 0.20784314 0.09019608]
  [0.54117647 0.30588235 0.17254902]]

 [[0.47843137 0.35686275 0.37647059]
  [0.50980392 0.38823529 0.40784314]


In [13]:
import pickle

pickle_out = open('x.pickle' , 'wb')
pickle.dump(X , pickle_out)
pickle_out.close()

pickle_out = open('y.pickle' , 'wb')
pickle.dump(Y , pickle_out)
pickle_out.close()

In [2]:
import pickle

pickle_in = open("x.pickle" , 'rb')
X = pickle.load(pickle_in)

pickle_in = open("y.pickle" , 'rb')
Y = pickle.load(pickle_in)

In [4]:
print(Y[-1] , X[0])

1 [[[0.94509804 0.95294118 0.90980392]
  [0.94117647 0.94901961 0.90588235]
  [0.9372549  0.94509804 0.90196078]
  ...
  [0.56862745 0.3254902  0.14117647]
  [0.55686275 0.31764706 0.13333333]
  [0.57647059 0.3372549  0.15294118]]

 [[0.91764706 0.9254902  0.88235294]
  [0.91764706 0.9254902  0.88235294]
  [0.90980392 0.91764706 0.8745098 ]
  ...
  [0.58431373 0.34117647 0.15686275]
  [0.57254902 0.32941176 0.14509804]
  [0.57254902 0.3372549  0.14117647]]

 [[0.87843137 0.88235294 0.85098039]
  [0.8745098  0.87843137 0.84705882]
  [0.87058824 0.8745098  0.84313725]
  ...
  [0.60392157 0.35294118 0.16470588]
  [0.59215686 0.34117647 0.15294118]
  [0.57254902 0.32941176 0.12941176]]

 ...

 [[0.47058824 0.34901961 0.36862745]
  [0.49803922 0.37647059 0.39607843]
  [0.52941176 0.40784314 0.42745098]
  ...
  [0.39215686 0.19607843 0.09019608]
  [0.43137255 0.20784314 0.09019608]
  [0.54117647 0.30588235 0.17254902]]

 [[0.47843137 0.35686275 0.37647059]
  [0.50980392 0.38823529 0.40784314

In [3]:
from keras import layers

from keras.losses import SparseCategoricalCrossentropy
from keras.applications import MobileNet

In [4]:
model = MobileNet(weights='imagenet' , include_top=False , input_shape=(224,224,3))


In [5]:
model.summary()

Model: "mobilenet_1.00_224"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 conv1 (Conv2D)              (None, 112, 112, 32)      864       
                                                                 
 conv1_bn (BatchNormalizatio  (None, 112, 112, 32)     128       
 n)                                                              
                                                                 
 conv1_relu (ReLU)           (None, 112, 112, 32)      0         
                                                                 
 conv_dw_1 (DepthwiseConv2D)  (None, 112, 112, 32)     288       
                                                                 
 conv_dw_1_bn (BatchNormaliz  (None, 112, 112, 32)     128       
 ation)                                         

In [6]:
base_input = model.layers[0].input


In [7]:
base_output = model.layers[-1].output

In [11]:
flat_layer = keras.layers.Flatten()(base_output)
final_output = keras.layers.Dense(128 , activation='relu' , name = 'my_layer_1')(flat_layer)
final_layer = keras.layers.Dense(3 , activation='softmax' , name = 'fully_connected_layer')(final_output)

In [12]:
new_version = keras.Model(inputs = base_input , outputs = final_layer)

In [11]:
new_version.save('untrained_v2')

INFO:tensorflow:Assets written to: untrained_v2\assets


INFO:tensorflow:Assets written to: untrained_v2\assets


In [13]:
new_version.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 conv1 (Conv2D)              (None, 112, 112, 32)      864       
                                                                 
 conv1_bn (BatchNormalizatio  (None, 112, 112, 32)     128       
 n)                                                              
                                                                 
 conv1_relu (ReLU)           (None, 112, 112, 32)      0         
                                                                 
 conv_dw_1 (DepthwiseConv2D)  (None, 112, 112, 32)     288       
                                                                 
 conv_dw_1_bn (BatchNormaliz  (None, 112, 112, 32)     128       
 ation)                                                    

In [14]:
new_version.compile(optimizer='adam' , loss = SparseCategoricalCrossentropy() , metrics = ['accuracy'])

In [15]:
from keras.callbacks import Callback
from keras.callbacks import ModelCheckpoint
from keras.callbacks import EarlyStopping

In [16]:
check_point = ModelCheckpoint(
    filepath = 'best_model.v2',
    monitor = 'val_accuracy',
    save_best_only=True,
    save_weights_only=False,
    mode='max',
    verbose=1
)

In [17]:
early_stopping = EarlyStopping(
    monitor='val_accuracy',
    patience=2,
    mode='max',
    verbose=1
)

In [18]:
for layer in new_version.layers[1:10]:
    layer.trainable = False

for layer in new_version.layers[10:]:
    layer.trainable = True

In [20]:
new_version.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 Conv1 (Conv2D)                 (None, 112, 112, 32  864         ['input_1[0][0]']                
                                )                                                                 
                                                                                                  
 bn_Conv1 (BatchNormalization)  (None, 112, 112, 32  128         ['Conv1[0][0]']                  
                                )                                                             

In [19]:
new_version.fit( X, Y , epochs = 5 , validation_split = 0.1  , batch_size = 64 , callbacks=[check_point , early_stopping])

Epoch 1/5
52/52 [==============================] - ETA: 0s - loss: 2.7381 - accuracy: 0.8868
Epoch 1: val_accuracy improved from -inf to 0.82880, saving model to best_model.v2


INFO:tensorflow:Assets written to: best_model.v2\assets


INFO:tensorflow:Assets written to: best_model.v2\assets


52/52 [==============================] - 373s 7s/step - loss: 2.7381 - accuracy: 0.8868 - val_loss: 5.6175 - val_accuracy: 0.8288
Epoch 2/5
52/52 [==============================] - ETA: 0s - loss: 0.0494 - accuracy: 0.9876
Epoch 2: val_accuracy improved from 0.82880 to 0.86957, saving model to best_model.v2


INFO:tensorflow:Assets written to: best_model.v2\assets


INFO:tensorflow:Assets written to: best_model.v2\assets


52/52 [==============================] - 351s 7s/step - loss: 0.0494 - accuracy: 0.9876 - val_loss: 2.6908 - val_accuracy: 0.8696
Epoch 3/5
52/52 [==============================] - ETA: 0s - loss: 0.0390 - accuracy: 0.9870
Epoch 3: val_accuracy improved from 0.86957 to 0.96467, saving model to best_model.v2


INFO:tensorflow:Assets written to: best_model.v2\assets


INFO:tensorflow:Assets written to: best_model.v2\assets


52/52 [==============================] - 345s 7s/step - loss: 0.0390 - accuracy: 0.9870 - val_loss: 0.3048 - val_accuracy: 0.9647
Epoch 4/5
52/52 [==============================] - ETA: 0s - loss: 0.0087 - accuracy: 0.9979
Epoch 4: val_accuracy improved from 0.96467 to 0.98098, saving model to best_model.v2


INFO:tensorflow:Assets written to: best_model.v2\assets


INFO:tensorflow:Assets written to: best_model.v2\assets


52/52 [==============================] - 345s 7s/step - loss: 0.0087 - accuracy: 0.9979 - val_loss: 0.1222 - val_accuracy: 0.9810
Epoch 5/5
52/52 [==============================] - ETA: 0s - loss: 0.0105 - accuracy: 0.9988
Epoch 5: val_accuracy did not improve from 0.98098
52/52 [==============================] - 327s 6s/step - loss: 0.0105 - accuracy: 0.9988 - val_loss: 0.2274 - val_accuracy: 0.9783


In [20]:
new_version.save('model_to_use_mobilenet_97')

INFO:tensorflow:Assets written to: model_to_use_mobilenet_97\assets


INFO:tensorflow:Assets written to: model_to_use_mobilenet_97\assets


Prediction

In [54]:
image = cv2.imread("C:\Projects\Dataset\WIN_20230607_12_37_09_Pro.jpg")
image = cv2.cvtColor(image , cv2.COLOR_BGR2RGB)
image = cv2.resize(image, (224,224))
image = np.expand_dims(image , axis=0)
print(image.shape)




(1, 224, 224, 3)


In [55]:
image = image/255.0



In [ ]:
model_load = keras.models.load_model('model_to_use_mobilenet_97')



In [56]:
prediction = model_load.predict(image)

print(np.argmax(prediction))

1/1 [==============================] - 0s 82ms/step
1
